(()=>{'use strict';
const KEY='copy-button-manager:v1',content=document.querySelector('#content'),count=document.querySelector('#count'),root=document.querySelector('#modal-root'),file=document.querySelector('#csv-file');
let items=[],editing=false,dragId=null;try{items=JSON.parse(localStorage.getItem(KEY)||'[]')}catch{}
const id=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random().toString(36).slice(2)}`,esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(s){document.querySelector('#toast-root').innerHTML=`<div class="toast" role="status">✓ ${esc(s)}</div>`;setTimeout(()=>document.querySelector('#toast-root').replaceChildren(),2400)}
function save(){localStorage.setItem(KEY,JSON.stringify(items));render()}
function render(){count.textContent=items.length?`${items.length} 個`:'';document.querySelector('#edit').textContent=editing?'完了':'編集';document.querySelector('#edit').classList.toggle('active',editing);
if(!items.length){content.innerHTML='<div class="emptyState"><div class="emptyIcon" aria-hidden="true"><span></span><span></span><span></span></div><h3>ボタンはまだありません</h3><p>右下の「＋」から、よく使う文字列を登録してください。</p></div>';return}
content.innerHTML=`<div class="buttonGrid">${items.map(x=>`<article data-button-id="${x.id}" class="copyCard ${editing?'editing':''}">${editing?`<button class="dragHandle" data-drag="${x.id}" aria-label="${esc(x.displayText)}を移動">⠿</button>`:''}<button class="copyArea" data-copy="${x.id}" ${editing?'disabled':''}><span class="copyGlyph">⧉</span><span>${esc(x.displayText)}</span></button>${x.note?`<span class="tooltip">${esc(x.note)}</span>`:''}${editing?`<div class="cardActions"><button data-edit="${x.id}" aria-label="編集">✎</button><button class="danger" data-delete="${x.id}" aria-label="削除">×</button></div>`:''}</article>`).join('')}</div>`}
function form(item){const isEdit=!!item;root.innerHTML=`<div class="modalBackdrop"><section class="modal" role="dialog" aria-modal="true"><div class="modalHeader"><div><span class="eyebrow">BUTTON SETTINGS</span><h2>${isEdit?'ボタンを編集':'新しいボタン'}</h2></div><button class="closeButton" type="button">×</button></div><form><label>表示文字列 <em>必須</em><input name="display" maxlength="80" required placeholder="例：メールアドレス" value="${esc(item?.displayText||'')}"></label><label>コピーする文字列<textarea name="copy" rows="4" placeholder="クリックしたときにコピーする内容">${esc(item?.copyText||'')}</textarea></label><label>補足 <span class="optional">任意・PCのみ表示</span><textarea name="note" rows="3" placeholder="マウスを合わせたときに表示する説明">${esc(item?.note||'')}</textarea></label><div class="modalActions"><button type="button" class="secondary cancel">キャンセル</button><button class="primary">${isEdit?'更新する':'追加する'}</button></div></form></section></div>`;
const close=()=>root.replaceChildren();root.querySelector('.closeButton').onclick=close;root.querySelector('.cancel').onclick=close;root.querySelector('form').onsubmit=e=>{e.preventDefault();const d=new FormData(e.currentTarget),next={id:item?.id||id(),displayText:d.get('display').trim(),copyText:d.get('copy'),note:d.get('note')};items=isEdit?items.map(x=>x.id===item.id?next:x):[...items,next];save();close();toast(isEdit?'ボタンを更新しました':'ボタンを追加しました')};root.querySelector('input').focus()}
content.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;const find=k=>items.find(x=>x.id===b.dataset[k]);if(b.dataset.copy&&!editing){const x=find('copy');try{await navigator.clipboard.writeText(x.copyText);toast(`「${x.displayText}」をコピーしました`)}catch{toast('コピーできませんでした。HTTPSで開いてください')}}if(b.dataset.edit)form(find('edit'));if(b.dataset.delete){const x=find('delete');if(confirm(`「${x.displayText}」を削除しますか？`)){items=items.filter(v=>v.id!==x.id);save();toast('ボタンを削除しました')}}});
content.addEventListener('pointerdown',e=>{const h=e.target.closest('[data-drag]');if(!h)return;dragId=h.dataset.drag;h.setPointerCapture(e.pointerId);document.body.classList.add('is-dragging')});content.addEventListener('pointermove',e=>{if(!dragId)return;const t=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-button-id]');if(!t||t.dataset.buttonId===dragId)return;const a=items.findIndex(x=>x.id===dragId),b=items.findIndex(x=>x.id===t.dataset.buttonId),m=items.splice(a,1)[0];items.splice(b,0,m);render()});const drop=()=>{if(dragId){dragId=null;document.body.classList.remove('is-dragging');save();toast('並び順を保存しました')}};content.addEventListener('pointerup',drop);content.addEventListener('pointercancel',drop);
document.querySelector('#add').onclick=()=>form();document.querySelector('#edit').onclick=()=>{editing=!editing;render()};document.querySelector('#import').onclick=()=>file.click();
const cell=v=>`"${String(v).replaceAll('"','""')}"`;document.querySelector('#export').onclick=()=>{if(!items.length)return toast('エクスポートするボタンがありません');const lines=[['order','display_text','copy_text','note'].map(cell).join(','),...items.map((x,i)=>[i+1,x.displayText,x.copyText,x.note].map(cell).join(','))],blob=new Blob(['\uFEFF'+lines.join('\r\n')],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`copy-buttons-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href);toast('CSVをエクスポートしました')};
function csv(text){text=text.replace(/^\uFEFF/,'');let rows=[],row=[],v='',q=false;for(let i=0;i<text.length;i++){let c=text[i];if(q){if(c==='"'&&text[i+1]==='"'){v+='"';i++}else if(c==='"')q=false;else v+=c}else if(c==='"')q=true;else if(c===','){row.push(v);v=''}else if(c==='\n'){row.push(v.replace(/\r$/,''));rows.push(row);row=[];v=''}else v+=c}if(q)throw Error('ダブルクォーテーションが閉じられていません。');if(v||row.length){row.push(v.replace(/\r$/,''));rows.push(row)}return rows.filter(r=>r.some(Boolean))}
file.onchange=async()=>{const f=file.files[0];file.value='';if(!f)return;try{const rows=csv(await f.text()),head=['order','display_text','copy_text','note'];if(!rows.length||head.some((x,i)=>rows[0][i]!==x))throw Error('1行目の列名が正しくありません。');const next=rows.slice(1).map((r,i)=>{if(r.length!==4)throw Error(`${i+2}行目の列数が正しくありません。`);if(!r[1].trim())throw Error(`${i+2}行目の表示文字列が空です。`);return{id:id(),displayText:r[1],copyText:r[2],note:r[3],order:+r[0]}}).sort((a,b)=>a.order-b.order).map(({order,...x})=>x);const mode=prompt(`${next.length}件を読み込みました。\n「置換」または「追加」と入力してください。`,'置換');if(mode===null)return;if(!['置換','追加'].includes(mode))throw Error('「置換」または「追加」を入力してください。');items=mode==='置換'?next:[...items,...next];save();toast(`${next.length}件をインポートしました`)}catch(e){toast(e.message||'CSVを読み込めませんでした')}};render();
})();
